In [9]:
!pip -q install slack_sdk requests
import os, urllib.parse, requests
from urllib.parse import urlparse, parse_qs

CLIENT_ID = "8048382690262.9605912667138"
CLIENT_SECRET = "f1ffa7f6d879af1108a11c241ec1f719"
REDIRECT_URI = "https://oauth.pstmn.io/v1/callback"

# ask for USER token scopes via user_scope (not scope)
USER_SCOPES = "im:read,im:history,mpim:read,mpim:history,users:read"

authorize_url = (
    "https://slack.com/oauth/v2/authorize?"
    + urllib.parse.urlencode({
        "client_id": CLIENT_ID,
        "user_scope": USER_SCOPES,        # <-- key change here
        "redirect_uri": REDIRECT_URI
    })
)
print("1) Open this URL and click Allow:\n", authorize_url)

# Paste FULL redirect URL; we’ll extract ?code=... safely
full_url = input("\n2) Paste the FULL redirect URL after Allow: ").strip()
code = parse_qs(urlparse(full_url).query).get("code", [None])[0]
assert code, "No 'code' found—make sure you pasted the entire URL with ?code=...&state=..."
print("Parsed code:", code)

# Exchange code for tokens
resp = requests.post("https://slack.com/api/oauth.v2.access", data={
    "client_id": CLIENT_ID,
    "client_secret": CLIENT_SECRET,
    "code": code,
    "redirect_uri": REDIRECT_URI
}).json()

print("Raw response:", resp)  # helpful if anything fails

if resp.get("ok"):
    # With user_scope, the user token is here:
    xoxp = (resp.get("authed_user") or {}).get("access_token")
    if xoxp:
        os.environ["SLACK_USER_TOKEN"] = xoxp
        print("✅ User token acquired:", xoxp[:18], "...")
    else:
        print("Got no user token. Did the consent screen show user access?")
else:
    print("❌ Exchange failed:", resp.get("error"))

1) Open this URL and click Allow:
 https://slack.com/oauth/v2/authorize?client_id=8048382690262.9605912667138&user_scope=im%3Aread%2Cim%3Ahistory%2Cmpim%3Aread%2Cmpim%3Ahistory%2Cusers%3Aread&redirect_uri=https%3A%2F%2Foauth.pstmn.io%2Fv1%2Fcallback

2) Paste the FULL redirect URL after Allow: https://oauth.pstmn.io/v1/callback?code=8048382690262.9604821088950.c27e66687bb3b3e1605555d64b2f1741578226832bdd38a206ab8c0aebfa6cec&state=
Parsed code: 8048382690262.9604821088950.c27e66687bb3b3e1605555d64b2f1741578226832bdd38a206ab8c0aebfa6cec
Raw response: {'ok': True, 'app_id': 'A09HTSUKM42', 'authed_user': {'id': 'U0829PC23J4', 'scope': 'im:history,mpim:history,im:read,mpim:read,users:read', 'access_token': 'xoxp-8048382690262-8077794071616-9600382724771-b7e066530726ea6f72a56c745808f25c', 'token_type': 'user'}, 'team': {'id': 'T081EB8LA7Q', 'name': 'SJSU_MSDA'}, 'enterprise': None, 'is_enterprise_install': False}
✅ User token acquired: xoxp-8048382690262 ...

In [10]:
!pip -q install slack_sdk pandas
from slack_sdk import WebClient
import pandas as pd
from datetime import datetime, timezone, timedelta

client = WebClient(token=os.environ["SLACK_USER_TOKEN"])

# Build user map (id -> display name)
users, cursor = [], None
while True:
    r = client.users_list(limit=200, cursor=cursor)
    users += r["members"]
    cursor = r.get("response_metadata", {}).get("next_cursor")
    if not cursor: break
user_map = {u["id"]: (u.get("profile",{}) or {}).get("real_name") or u.get("name") or u["id"] for u in users}

# 1:1 DMs (IMs)
ims, cursor = [], None
while True:
    r = client.conversations_list(types="im", limit=1000, cursor=cursor)
    ims += r["channels"]
    cursor = r.get("response_metadata", {}).get("next_cursor")
    if not cursor: break

target = next((im for im in ims if "ketki" in user_map.get(im.get("user"),"").lower()), None)

# If not found as IM, look in group DMs (MPIMs)
if not target:
    mpims, cursor = [], None
    while True:
        r = client.conversations_list(types="mpim", limit=1000, cursor=cursor)
        mpims += r["channels"]
        cursor = r.get("response_metadata", {}).get("next_cursor")
        if not cursor: break
    for c in mpims:
        mems = client.conversations_members(channel=c["id"])["members"]
        names = [user_map.get(m,"").lower() for m in mems]
        if any("ketki" in n for n in names):
            target = c; break

assert target, "Couldn't find a DM/Group DM with Ketki that your user is in."

channel_id = target["id"]
print("Using conversation:", channel_id)

# Fetch last 30 days (paged)
rows, cursor = [], None
oldest = str((datetime.now(tz=timezone.utc) - timedelta(days=30)).timestamp())
while True:
    r = client.conversations_history(channel=channel_id, oldest=oldest, limit=200, cursor=cursor)
    for m in r.get("messages", []):
        if m.get("type") != "message": continue
        ts = float(m["ts"])
        rows.append({
            "ts_iso": datetime.fromtimestamp(ts, tz=timezone.utc).isoformat(),
            "from": user_map.get(m.get("user") or m.get("bot_id"), "unknown"),
            "text": m.get("text",""),
            "thread_ts": m.get("thread_ts"),
        })
    cursor = r.get("response_metadata", {}).get("next_cursor")
    if not cursor: break

df = pd.DataFrame(rows).sort_values("ts_iso")
print("Messages fetched:", len(df))
df.tail(10)
df.to_csv("/content/ketki_dm_messages.csv", index=False)
print("Saved → /content/ketki_dm_messages.csv")

Using conversation: D09HN0AST6X
Messages fetched: 1
Saved → /content/ketki_dm_messages.csv

In [12]:
!pip -q install slack_sdk pandas
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
import pandas as pd
from datetime import datetime, timezone
import time, os

# --- requires: os.environ["SLACK_USER_TOKEN"] = xoxp-... ---
token = os.environ.get("SLACK_USER_TOKEN")
assert token and token.startswith(("xoxp","xoxa")), "Set SLACK_USER_TOKEN to your user token (xoxp-...)."
client = WebClient(token=token)

# Build user map (id -> display name) with pagination
users, cursor = [], None
while True:
    r = client.users_list(limit=200, cursor=cursor)
    users += r["members"]
    cursor = r.get("response_metadata", {}).get("next_cursor")
    if not cursor: break

def display_name(uid):
    u = next((x for x in users if x["id"] == uid), None)
    if not u: return uid
    prof = (u.get("profile") or {})
    return prof.get("real_name") or u.get("name") or uid

def list_all(types):
    items, cur = [], None
    while True:
        resp = client.conversations_list(types=types, limit=1000, cursor=cur)
        items += resp["channels"]
        cur = resp.get("response_metadata", {}).get("next_cursor")
        if not cur: break
    return items

def last_message(channel_id):
    try:
        resp = client.conversations_history(channel=channel_id, limit=1)
        msgs = resp.get("messages", [])
        if not msgs: return None
        m = msgs[0]
        ts = float(m["ts"])
        return {
            "last_ts": ts,
            "last_ts_iso": datetime.fromtimestamp(ts, tz=timezone.utc).isoformat(),
            "last_sender_id": m.get("user") or m.get("bot_id"),
            "last_sender_name": display_name(m.get("user") or m.get("bot_id") or "unknown"),
            "last_text": m.get("text","")
        }
    except SlackApiError as e:
        # basic rate-limit/backoff
        if e.response["error"] == "ratelimited":
            time.sleep(2)
            return last_message(channel_id)
        return None

rows = []

# --- 1:1 DMs (IMs) ---
ims = list_all("im")
for im in ims:
    other_uid = im.get("user")
    info = last_message(im["id"]) or {}
    rows.append({
        "type": "im",
        "channel_id": im["id"],
        "participants": display_name(other_uid),
        **info
    })

# --- Group DMs (MPIMs) ---
mpims = list_all("mpim")
for c in mpims:
    mems = client.conversations_members(channel=c["id"])["members"]
    names = ", ".join(sorted(display_name(m) for m in mems))
    info = last_message(c["id"]) or {}
    rows.append({
        "type": "mpim",
        "channel_id": c["id"],
        "participants": names,
        **info
    })

df = pd.DataFrame(rows)
# sort by most recent last message
if "last_ts" in df.columns:
    df = df.sort_values("last_ts", ascending=False).drop(columns=["last_ts"])
else:
    df = df.sort_values("participants")

print("Conversations found:", len(df))
df.head(20)
df.to_csv("/content/slack_dms_index.csv", index=False)
print("Saved → /content/slack_dms_index.csv")

Conversations found: 5
Saved → /content/slack_dms_index.csv

In [13]:
!ls -lh /content/slack_dms_index.csv
import pandas as pd
pd.read_csv("/content/slack_dms_index.csv").head()

-rw-r--r-- 1 root root 643 Sep 30 03:55 /content/slack_dms_index.csv

,type,channel_id,participants,last_ts_iso,last_sender_id,last_sender_name,last_text
0,im,D09HUD7RYRY,hiru01,2025-09-30T03:53:02.770449+00:00,U0829PC23J4,Debika Choudhury,"Hi Hirok,\n\nCan we have a sync up call tomorr..."
1,im,D09HN0AST6X,ketkimaddiwar94,2025-09-30T01:54:16.425019+00:00,U0829PC23J4,Debika Choudhury,Hi Ketki! Can we meet *tomorrow at 3:00 PM PT*...
2,im,D0816DLJ4LX,Slackbot,2024-12-16T16:41:36.453919+00:00,USLACKBOT,Slackbot,An invitation link that you created will expir...
3,im,D09J7A6781X,Demo Bot,NaN,NaN,NaN,NaN
4,im,D081PEZT204,Debika Choudhury,NaN,NaN,NaN,NaN

In [16]:
!pip -q install slack_sdk pandas
from slack_sdk import WebClient
import pandas as pd
from datetime import datetime, timezone, timedelta
import os

TARGET_NAMES = ["ketki", "hiru"]   # case-insensitive
DAYS = 30
OUT_CSV = "/content/dms_ketki_hirok_mine_final.csv"
KEYWORDS = r"tomorrow|meeting|schedule|invite"   # set to "" to disable keyword filter

token = os.environ.get("SLACK_USER_TOKEN")
assert token and token.startswith(("xoxp","xoxa")), "Set SLACK_USER_TOKEN to your user token."
client = WebClient(token=token)

# Identity
me = client.auth_test()
my_user_id = me["user_id"]

# Users map
users, cur = [], None
while True:
    r = client.users_list(limit=200, cursor=cur)
    users += r["members"]
    cur = r.get("response_metadata", {}).get("next_cursor")
    if not cur: break

def display_name(u):
    prof = (u.get("profile") or {})
    return prof.get("real_name") or u.get("name") or u["id"]

user_map = {u["id"]: display_name(u) for u in users}

# List all 1:1 DMs
ims, cur = [], None
while True:
    r = client.conversations_list(types="im", limit=1000, cursor=cur)
    ims += r["channels"]
    cur = r.get("response_metadata", {}).get("next_cursor")
    if not cur: break

def name_matches(uid, targets):
    name = user_map.get(uid, "").lower()
    return any(t.lower() in name for t in targets)

target_ims = [im for im in ims if name_matches(im.get("user"), TARGET_NAMES)]
assert target_ims, "No 1:1 DMs found for: " + ", ".join(TARGET_NAMES)

# Fetch history helper
def fetch_history(channel_id, days=DAYS):
    rows, cursor = [], None
    oldest = str((datetime.now(tz=timezone.utc) - timedelta(days=days)).timestamp())
    while True:
        resp = client.conversations_history(channel=channel_id, oldest=oldest, limit=200, cursor=cursor)
        for m in resp.get("messages", []):
            if m.get("type") != "message": continue
            ts = float(m["ts"])
            sender_id = m.get("user") or m.get("bot_id")
            rows.append({
                "channel_id": channel_id,
                "ts_iso": datetime.fromtimestamp(ts, tz=timezone.utc).isoformat(),
                "sender_id": sender_id,
                "sender_name": user_map.get(sender_id, "unknown"),
                "text": m.get("text",""),
                "dm_with": user_map.get(next(im.get("user") for im in target_ims if im["id"]==channel_id), "unknown"),
            })
        cursor = resp.get("response_metadata", {}).get("next_cursor")
        if not cursor: break
    return pd.DataFrame(rows)

# Combine both DMs
frames = [fetch_history(im["id"], days=DAYS) for im in target_ims]
msgs = pd.concat(frames, ignore_index=True)

# Keep only messages YOU sent
mine = msgs[msgs["sender_id"] == my_user_id].copy()

# Optional: filter by keywords (non-capturing regex → no warning)
if KEYWORDS:
    mine = mine[mine["text"].str.contains(r"(?:%s)" % KEYWORDS, case=False, regex=True, na=False)]

# De-dupe in case same line shows in multiple views
mine = mine.drop_duplicates(subset=["channel_id","ts_iso","text"]).sort_values("ts_iso")

# Show once + save
print("Your messages matched:", len(mine))
display(mine.tail(20))
mine.to_csv(OUT_CSV, index=False)
print("Saved →", OUT_CSV)

Your messages matched: 2

,channel_id,ts_iso,sender_id,sender_name,text,dm_with
1,D09HN0AST6X,2025-09-30T01:54:16.425019+00:00,U0829PC23J4,Debika Choudhury,Hi Ketki! Can we meet *tomorrow at 3:00 PM PT*...,ketkimaddiwar94
0,D09HUD7RYRY,2025-09-30T03:53:02.770449+00:00,U0829PC23J4,Debika Choudhury,"Hi Hirok,\n\nCan we have a sync up call tomorr...",hiru01

Saved → /content/dms_ketki_hirok_mine_final.csv